version: "3.8"

services:
  database:
    image: postgres:15-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - this_project

  database_test:
    image: postgres:15-alpine
    ports:
      - '6433:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    networks:
      - this_project

#  pgadmin:
#    image: dpage/pgadmin4
#    restart: always
#    ports:
#      - "8888:80"
#    environment:
#      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com
#      PGADMIN_DEFAULT_PASSWORD: pgadmin
#    volumes:
#      - pgadmin-data:/var/lib/pgadmin
#    networks:
#      - this_project


volumes:
  database_data:
    driver: local
  pgadmin-data:
    driver: local
networks:
  this_project:
    driver: bridge